### ISSUE TITLE
Unexpected duplicate "border"

### ISSUE THREAD

**Issue by margittennosaar** [jagriti99/react_taste-it#1]
https://github.com/jagriti99/react_taste-it/blob/efbc9184e4a890672e1e41c241c4c7ff8cee9122/src/components/Card.module.css#L34

**Comment by jagriti99** [comment]
fixed it
https://github.com/jagriti99/react_taste-it/commit/8988e0d5dab99286ce4b68166b8084d350fd5979#diff-c809c111b18b2733b5822c68303f062171f94d9733a561e7be83a6c0712bf952L34
