### ISSUE TITLE
Unexpected unit

### ISSUE THREAD

**Issue by margittennosaar** [jagriti99/react_taste-it#2]
https://github.com/jagriti99/react_taste-it/blob/efbc9184e4a890672e1e41c241c4c7ff8cee9122/src/components/Recipe.module.css#L3

Instead of using 0px, use just 0 - for example here and in the future: **a { top: 0 }**

**Comment by jagriti99** [comment]
fixed it
https://github.com/jagriti99/react_taste-it/commit/8988e0d5dab99286ce4b68166b8084d350fd5979#diff-d811255e904a2e3d4a2a42a7594f25687c5710c0fc99aceb57bff7ba501a249aL3
