### ISSUE TITLE
remove console logs

### ISSUE THREAD

**Issue by margittennosaar** [jagriti99/react_taste-it#5]
https://github.com/jagriti99/react_taste-it/blob/efbc9184e4a890672e1e41c241c4c7ff8cee9122/src/components/AddNewRecipe.jsx#L24

**Comment by jagriti99** [comment]
removed it 
https://github.com/jagriti99/react_taste-it/commit/8988e0d5dab99286ce4b68166b8084d350fd5979#diff-f7b6c5504a02ae76b256dff66c51affa4e2e1573f2dbf9466949ffe2df8536b9R24
