### ISSUE TITLE
Circle() can not be empty

### ISSUE THREAD

**Issue by margittennosaar** [jagriti99/react_taste-it#6]
https://github.com/jagriti99/react_taste-it/blob/efbc9184e4a890672e1e41c241c4c7ff8cee9122/src/components/SeemoreRecipes.module.css#L15

**Comment by jagriti99** [comment]
fixed it
https://github.com/jagriti99/react_taste-it/commit/8988e0d5dab99286ce4b68166b8084d350fd5979#diff-9992e2f096fc69183b7d5f469828e6fe55570522dec1fb78b4b7d7ac8f7956beR15
