### ISSUE TITLE
0.4 missing seconds unit

### ISSUE THREAD

**Issue by margittennosaar** [jagriti99/react_taste-it#8]
https://github.com/jagriti99/react_taste-it/blob/efbc9184e4a890672e1e41c241c4c7ff8cee9122/src/components/Nav.module.css#L28

**Comment by jagriti99** [comment]
removed it 
https://github.com/jagriti99/react_taste-it/commit/8988e0d5dab99286ce4b68166b8084d350fd5979#diff-02b244cb3659d8bd9e0af726a9a259db4271f20145ef3b49ca225b7c8711cf58L28
